// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1ns / 1ps

module ocnn6_net_8_layer_pipeline_bitset_512ns_512ns_32s_1ns_512_1_1 (sel,din,value,dout);

parameter ADDRWIDTH = 32;
parameter DATAWIDTH = 512;


input [ADDRWIDTH-1:0] sel;
input [DATAWIDTH-1:0] din;
input value;
output [DATAWIDTH-1:0] dout;

reg [DATAWIDTH-1:0] out_tmp;



always @ (*) begin
    out_tmp = din;
    out_tmp[sel] = |value;
end




assign dout = out_tmp;




endmodule
