set ModuleHierarchy {[{
"Name" : "minkowski_net_14_layer_pipeline","ID" : "0","Type" : "sequential",
"SubInsts" : [
	{"Name" : "grp_pipeline_bitmap_stage_fu_462","ID" : "1","Type" : "sequential",
		"SubInsts" : [
		{"Name" : "grp_streaming_bitmap_constructor_fu_74","ID" : "2","Type" : "sequential",
			"SubLoops" : [
			{"Name" : "VITIS_LOOP_105_1","ID" : "3","Type" : "pipeline"},
			{"Name" : "VITIS_LOOP_109_2","ID" : "4","Type" : "pipeline"},
			{"Name" : "VOXEL_PROCESSING","ID" : "5","Type" : "pipeline"},
			{"Name" : "L2_CONSTRUCTION_VITIS_LOOP_134_3","ID" : "6","Type" : "pipeline"},
			{"Name" : "VITIS_LOOP_176_8","ID" : "7","Type" : "pipeline"},
			{"Name" : "VITIS_LOOP_189_9","ID" : "8","Type" : "pipeline"},]},]},
	{"Name" : "grp_final_layer_output_reconstruction_fu_546","ID" : "9","Type" : "sequential",
		"SubLoops" : [
		{"Name" : "INIT_FULL_OUTPUT","ID" : "10","Type" : "pipeline"},
		{"Name" : "RECONSTRUCT_FULL_CUBIC_VITIS_LOOP_417_1_VITIS_LOOP_418_2","ID" : "11","Type" : "pipeline"},]},],
"SubLoops" : [
	{"Name" : "VITIS_LOOP_96_1","ID" : "12","Type" : "pipeline"},
	{"Name" : "LAYER_PROCESSING","ID" : "13","Type" : "no",
	"SubInsts" : [
	{"Name" : "grp_layer_convolution_with_persistent_accelerator_fu_496","ID" : "14","Type" : "sequential",
			"SubLoops" : [
			{"Name" : "PROCESS_PRUNED_VOXELS","ID" : "15","Type" : "no",
			"SubInsts" : [
			{"Name" : "grp_layer_convolution_with_persistent_accelerator_Outline_INIT_OUTPUT_BIAS_fu_3295","ID" : "16","Type" : "sequential",
					"SubLoops" : [
					{"Name" : "INIT_OUTPUT_BIAS","ID" : "17","Type" : "no"},]},
			{"Name" : "grp_layer_convolution_with_persistent_accelerator_Outline_READ_NEIGHBOR_FEATURES_fu_3303","ID" : "18","Type" : "sequential",
					"SubLoops" : [
					{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "19","Type" : "no"},]},],
			"SubLoops" : [
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "20","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "21","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "22","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "23","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "24","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "25","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "26","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "27","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "28","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "29","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "30","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "31","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "32","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "33","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "34","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "35","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "36","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "37","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "38","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "39","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "40","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "41","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "42","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "43","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "44","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "45","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "46","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "47","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "48","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "49","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "50","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "51","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "52","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "53","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "54","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "55","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "56","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "57","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "58","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "59","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "60","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "61","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "62","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "63","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "64","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "65","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "66","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "67","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "68","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "69","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "70","Type" : "pipeline"},
			{"Name" : "READ_NEIGHBOR_FEATURES","ID" : "71","Type" : "no"},
			{"Name" : "CONV_ACCUMULATE_VITIS_LOOP_288_1","ID" : "72","Type" : "pipeline"},
			{"Name" : "RELU_ACTIVATION","ID" : "73","Type" : "no"},
			{"Name" : "WRITE_OUTPUT_CROSS_ROW","ID" : "74","Type" : "pipeline"},
			{"Name" : "WRITE_OUTPUT_DIRECT","ID" : "75","Type" : "pipeline"},]},]},]},]
}]}